name: FORCE RUN 777

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: STEP 1
        run: echo "STEP IS RUNNING"

      - name: STEP 2
        run: echo "SECOND STEP"

      - name: TELEGRAM TEST
        run: |
          echo "TRYING TELEGRAM"